[project]
name = "adventofcode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "attrs>=25.4.0",
    "numpy>=2.3.5",
    "rich>=14.2.0",
    "scipy>=1.16.3",
    "scipy-stubs>=1.16.3.2",
    "z3-solver>=4.15.4.0",
]
